name: flutter_unisdk
description: "Универсальный Flutter плагин для интеграции мобильных сервисов (Huawei HMS и Google Firebase)"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  # Google Firebase зависимости
  firebase_core: ^4.0.0
  firebase_remote_config: ^6.0.0
  firebase_messaging: ^16.0.0
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0
  # Huawei HMS зависимости
  huawei_push:
    git:
      url: https://github.com/norutplz/hms-flutter-plugin.git
      ref: hms_push_flutter_3.29
      path: flutter-hms-push
  huawei_ads:
    git:
      url: https://github.com/norutplz/hms-flutter-plugin.git
      ref: hms_push_flutter_3.29
      path: flutter-hms-ads
  # Общие зависимости (для обоих провайдеров)
  huawei_hmsavailability:
    git:
      url: https://github.com/norutplz/hms-flutter-plugin.git
      ref: hms_push_flutter_3.29
      path: flutter-hms-availability

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

executables:
  setup: setup
