name: flutter_unisdk
description: "Универсальный Flutter плагин для интеграции мобильных сервисов (Huawei HMS и Google Firebase)"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

executables:
  setup: setup
